Actualizacion de descripcion
wilmacruz/RepositorySeleniumTest pull request #3
Opened 2023-10-21 14:21 UTC by wilmacruz

2023-10-21 14:30 UTC, ErraticTurtle35 requested changes

2023-10-21 14:30 UTC, ErraticTurtle35 commented on README.md
> +Una breve descripción de tu proyecto va aquí. Explica qué hace tu proyecto, qué utilidades podría tener y qué motivó su creación.
@wilmacruz 

Tocara acomodar una breve descripcion de lo que queremos que haga el proyecto. Para marcar el horizonte. 

En reuniones pasadas hablamos de un webscrapper

2023-10-21 14:30 UTC, ErraticTurtle35 commented on README.md
> +Qué cosas necesitas para instalar el software y cómo instalarlas.
La lista de herramientas que hemos instalado para trabajar en el proyecto

A grandes rasgos:
- Selenium Webdriver
- Katilum
- etc, etc

Todos estos tienen que tener link a de donde los hemos descargados y las versiones que estamos usando :)

2023-10-21 14:30 UTC, ErraticTurtle35 commented on README.md
> +- Java (versión)
Igualmente la version de java y la de los navegadores donde vamos a estar probando :)

2023-10-21 14:30 UTC, ErraticTurtle35 commented on README.md
> +Copy code
Estos bloques tiene que verse como codigo 

Y son los pasos para clonar el repositorio aun nos faltan pasao porque aun no hemos desarrollado todo pero por ahora te pediria que lo vuelvas bloques de codigo 

ejemplo 

```bash
git init
```

2023-10-21 14:30 UTC, ErraticTurtle35 commented on README.md
> +Explica qué sistema de versionado utilizas, si es aplicable.
Hora de investigar un poco XD 

Tocara definir como estaran estrucurados los PR los mensajes y el flujo de git

GitFlow o TrunchBase

2023-10-21 14:30 UTC, ErraticTurtle35 commented on README.md
> +Nombre del Autor - Trabajo Inicial - PerfilDelAutor
Tu nombre y redes sociales ;)

2023-11-21 13:20 UTC, wilmacruz commented on README.md
> +Nombre del Autor - Trabajo Inicial - PerfilDelAutor
Hii Gabriel, @ErraticTurtle35  ise los cambios pero no los veo alguna ayuda ? 
al final ise Branch > Merge Branch..

2023-11-21 13:20 UTC, merged

2023-11-21 13:56 UTC, wilmacruz commented on README.md
> +Explica qué sistema de versionado utilizas, si es aplicable.
Hi Gabriel, 
a mi pensar seria gitflow 

vi algunas de sus clases interesante
https://github.com/mouredev/hello-git

*CrunchBase

Saludos.!!